# Generated by Django 3.1.4 on 2024-10-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='refister',
            new_name='register',
        ),
    ]
